<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>probe</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.13" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.13" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.13" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.0.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\TheGambler.csproj" />
  </ItemGroup>
</Project>
